Recipes data discovery

In [1]:
from pathlib import Path
from fractions import Fraction
import pandas as pd
import numpy as np
import os

In [5]:
notebook_dir = os.getcwd() 
sql_dir = os.path.join(notebook_dir, 'sql_data')

Create tables_df's

In [100]:
file_paths = []
    # Walk through the directory and its subdirectories
for root, directories, files in os.walk(sql_dir):
    for filename in files:
            # Get the full file path
            file_path = os.path.join(root, filename)
            # Append the file path to the list
            file_paths.append(file_path)

for files in file_paths:
      print(files)

c:\Users\lmpro\Documents\GitHub\pantryplan\src\sql_data\recipes.csv
c:\Users\lmpro\Documents\GitHub\pantryplan\src\sql_data\recipe_ingredients.csv
c:\Users\lmpro\Documents\GitHub\pantryplan\src\sql_data\recipe_nutrition.csv
c:\Users\lmpro\Documents\GitHub\pantryplan\src\sql_data\recipe_steps.csv
c:\Users\lmpro\Documents\GitHub\pantryplan\src\sql_data\recipe_times.csv

In [101]:
df_recipe= pd.read_csv(file_paths[0])
df_recipe.head()

C:\Users\lmpro\AppData\Local\Temp\ipykernel_13760\3488173994.py:1: DtypeWarning: Columns (7,35,37,38,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df_recipe= pd.read_csv(file_paths[0])

,Unnamed: 0,id_recipe,name,Prep Time:,Cook Time:,Total Time:,Servings:,Servings Per Recipe,Calories,Total Fat,...,Rest Time:,Active Time:,Bake Time:,Grill Time:,Rise Time:,Fry Time:,Other Time Time:,Roast Time:,Process Time:,Release Pressure Time:
0,0,7970816,Air Fryer Honey-Mustard Chicken Thighs,5 mins,15 mins,20 mins,4,4.0,364.0,20g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,7814346,Air Fryer Hearts of Palm Sticks,15 mins,12 mins,47 mins,2,2.0,257.0,7g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,7560981,Air Fryer Cheesy Bacon Ranch French Fries,5 mins,15 mins,20 mins,4,4.0,527.0,29g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7509612,Air Fryer Mini Dark Chocolate Cake with Brown ...,20 mins,25 mins,1 hr 15 mins,6,6.0,331.0,16g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,7510155,Air Fryer Spanakopita,40 mins,15 mins,55 mins,24,24.0,122.0,7g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Clean recipe

In [102]:
#remove indexes
df_recipe.info()
#df_recipe=df_recipe.iloc[:,2:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18650 entries, 0 to 18649
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              18650 non-null  int64
 1   id_recipe               18650 non-null  int64
 2   name                    18650 non-null  object
 3   Prep Time:              18061 non-null  object
 4   Cook Time:              15739 non-null  object
 5   Total Time:             18173 non-null  object
 6   Servings:               18602 non-null  object
 7   Servings Per Recipe     18375 non-null  object
 8   Calories                18417 non-null  float64
 9   Total Fat               18182 non-null  object
 10  Saturated Fat           17585 non-null  object
 11  Cholesterol             15554 non-null  object
 12  Sodium                  18412 non-null  object
 13  Total Carbohydrate      18396 non-null  object
 14  Dietary Fiber           17910 non-null  object
 15  Total Sugars            16925 non-null  object
 16  Protein                 18355 non-null  object
 17  Vitamin C               15762 non-null  object
 18  Calcium                 17671 non-null  object
 19  Iron                    17487 non-null  object
 20  Potassium               18408 non-null  object
 21  Average_Review          17420 non-null  float64
 22  Review_Count            17420 non-null  object
 23  Freeze Time:            47 non-null     object
 24  Cool Time:              225 non-null    object
 25  Stand Time:             125 non-null    object
 26  Chill Time:             124 non-null    object
 27  Yield:                  12509 non-null  object
 28  Soak Time:              17 non-null     object
 29  Marinate Time:          48 non-null     object
 30  Additional Time:        6378 non-null   object
 31  Refrigerate Time:       45 non-null     object
 32  Rest Time:              53 non-null     object
 33  Active Time:            34 non-null     object
 34  Bake Time:              104 non-null    object
 35  Grill Time:             1 non-null      object
 36  Rise Time:              49 non-null     object
 37  Fry Time:               3 non-null      object
 38  Other Time Time:        2 non-null      object
 39  Roast Time:             6 non-null      object
 40  Process Time:           1 non-null      object
 41  Release Pressure Time:  12 non-null     object
dtypes: float64(2), int64(2), object(38)
memory usage: 6.0+ MB

In [23]:
df_recipe.columns=df_recipe.columns.str.lower().str.replace(' ','_').str.replace(':','')

In [31]:
time_columns = [col for col in df_recipe.columns if 'time' in col.lower() or 'id_recipe' in col.lower()]

df_times = df_recipe[time_columns]

In [41]:
time_columns = [col for col in df_recipe.columns if ('time' not in col.lower() and "serving" not in col.lower()) or "id_recipe" in col.lower() ]
df_nutrition=df_recipe[time_columns]

In [65]:
df_nutrition=df_nutrition.iloc[:,:14]
n = "recipe_nutrition.csv"

In [66]:
df_nutrition.drop_duplicates()

,id_recipe,calories,total_fat,saturated_fat,cholesterol,sodium,total_carbohydrate,dietary_fiber,total_sugars,protein,vitamin_c,calcium,iron,potassium
0,7970816,364.0,20g,6g,201mg,612mg,10g,1g,9g,38g,0mg,25mg,2mg,438mg
1,7814346,257.0,7g,2g,98mg,1497mg,37g,6g,1g,14g,16mg,220mg,8mg,462mg
2,7560981,527.0,29g,5g,7mg,1253mg,61g,5g,2g,9g,20mg,101mg,2mg,1152mg
3,7509612,331.0,16g,8g,57mg,286mg,46g,1g,39g,3g,2mg,44mg,2mg,75mg
4,7510155,122.0,7g,4g,16mg,194mg,12g,1g,0g,4g,3mg,85mg,2mg,140mg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18645,6584226,205.0,8g,1g,16mg,205mg,31g,2g,18g,3g,5mg,66mg,1mg,91mg
18646,6592849,190.0,9g,1g,24mg,183mg,26g,2g,13g,4g,3mg,35mg,1mg,116mg
18647,6586117,242.0,10g,2g,31mg,184mg,36g,1g,23g,3g,3mg,23mg,1mg,74mg
18648,6599517,561.0,17g,3g,70mg,539mg,99g,6g,62g,8g,6mg,59mg,1mg,137mg
18649,6562167,302.0,16g,10g,25mg,211mg,38g,1g,21g,4g,2mg,30mg,1mg,101mg

In [67]:
df_nutrition.to_csv(f'{sql_dir}\{n}',index=False)

In [68]:
df_times=df_times.drop_duplicates()
df_times

,id_recipe,prep_time,cook_time,total_time,freeze_time,cool_time,stand_time,chill_time,soak_time,marinate_time,...,rest_time,active_time,bake_time,grill_time,rise_time,fry_time,other_time_time,roast_time,process_time,release_pressure_time
0,7970816,5 mins,15 mins,20 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7814346,15 mins,12 mins,47 mins,20 mins,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7560981,5 mins,15 mins,20 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7509612,20 mins,25 mins,1 hr 15 mins,NaN,30 mins,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7510155,40 mins,15 mins,55 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18645,6584226,20 mins,50 mins,1 hr 20 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18646,6592849,20 mins,1 hr,2 hrs 20 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18647,6586117,15 mins,50 mins,1 hr 15 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18648,6599517,20 mins,50 mins,1 hr 10 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18649,6562167,20 mins,35 mins,55 mins,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
n = "recipe_times.csv"
df_times.to_csv(f'{sql_dir}\{n}',index=False)

In [61]:
n = "recipe_ingredients.csv"
df_ing=pd.read_csv(f'{sql_dir}\{n}')
df_ing['quantity']=df_ing['quantity'].astype(str)

In [62]:
value_to_drop = 'toppings of choice, e.g. maple syrup or fruit, for serving'
df_ing = df_ing[~(df_ing['quantity'] == value_to_drop)]
df_ing=df_ing.reset_index(drop=True)
df_ing=df_ing.replace('nan','')

In [63]:
df_ing['quantity']

0           4
1         1/2
2         1/2
3         1/2
4         1/4
         ...
123593      Â¼
123594      1
123595      1
123596     18
123597      2
Name: quantity, Length: 123598, dtype: object

In [ ]:
for index, row in df_ing.iterrows():
    quantity = row['quantity'].strip()  # Remove leading/trailing spaces
    if " to " in quantity:  # Check if " to " is present
        range_parts = quantity.split(" to ")
        a = range_parts[0].strip()
        b = range_parts[1].strip()
        
        # Check if a contains fractions
        if "/" in a:
            a = a.split()
            s = 0
            for val in a:
                if "/" in val:
                    frac_a = Fraction(val)
                    s += frac_a
                else:
                    s += int(val.strip())
        else:
            s = float(a)
        a = float(s)
        
        # Check if b contains fractions
        if "/" in b:
            b = b.split()
            s = 0
            for val in b:
                if "/" in val:
                    frac_b = Fraction(val)
                    s += frac_b
                else:
                    s += int(val.strip())
        else:
            s = float(b)
        b = float(s)
        
        q = (b + a) / 2
        df_ing.at[index, "quantity"] = q
        print([row['quantity'], "original ^", q])

Split the Ors

In [55]:
for index, row in df_ing.iterrows():
    quantity = row['quantity'].strip()  # Remove leading/trailing spaces
    if " or " in quantity:  # Check if " to " is present
        range_parts = quantity.split(" or ")
        a = range_parts[0].strip()
        b = range_parts[1].strip()
        
        # Check if a contains fractions
        if "/" in a:
            a = a.split()
            s = 0
            for val in a:
                if "/" in val:
                    frac_a = Fraction(val)
                    s += frac_a
                else:
                    s += int(val.strip())
        else:
            s = float(a)
        a = float(s)
        
        # Check if b contains fractions
        if "/" in b:
            b = b.split()
            s = 0
            for val in b:
                if "/" in val:
                    frac_b = Fraction(val)
                    s += frac_b
                else:
                    s += int(val.strip())
        else:
            s = float(b)
        b = float(s)
        
        q = (b + a) / 2
        df_ing.at[index, "quantity"] = q
        print([row['quantity'], "original ^", q])

['2 or 3', 'original ^', 2.5]
['3 or 4', 'original ^', 3.5]

In [2]:
nan_mask = df_ing['quantity'].isna() | df_ing['quantity'].str.lower().eq('nan')

# Filter the DataFrame to get rows with NaN or "nan"
nan_rows = df_ing[nan_mask]

df_ing[nan_mask]

NameError: name 'df_ing' is not defined

In [97]:
qty = df_ing['quantity']
for i in qty:
    for x in i:
        if x.isalpha():
                print(i)

TypeError: 'float' object is not iterable

In [3]:

n = "recipe_ingredients.csv"
df_ing.to_csv(f'{sql_dir}\{n}',index=False)

NameError: name 'df_ing' is not defined

Go back and fix the recipe dictionary

In [27]:
file = "recipes.csv"
df_recipe= pd.read_csv(f"{sql_dir}\{file}")

In [28]:
df_recipe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18650 entries, 0 to 18649
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           18650 non-null  int64
 1   id_recipe            18650 non-null  int64
 2   name                 18650 non-null  object
 3   total_time           18173 non-null  object
 4   servings             18602 non-null  object
 5   servings_per_recipe  18375 non-null  object
 6   calories             18417 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 1020.1+ KB

In [29]:
df_recipe.columns=df_recipe.columns.str.lower().str.replace(' ','_').str.replace(':','')

In [34]:
df_recipe = df_recipe.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [43]:
df_recipe['servings']=df_recipe['servings'].str.lower().str.replace("servings","").str.strip()

In [53]:
del df_recipe['servings']

KeyError: 'servings'

In [45]:
file = "recipes.csv"
df_recipe.to_csv(f"{sql_dir}\{file}", index=False)